# Generated by Django 2.2.5 on 2019-11-23 11:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webay', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='winner_notified',
        ),
    ]
