# Generated by Django 2.2.5 on 2019-11-18 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webay', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='item_pic',
            field=models.ImageField(upload_to='webay/media/item_pics'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='profile_pic',
            field=models.ImageField(default='default.jpg', upload_to='webay/media/profile_pics'),
        ),
    ]
