# Generated by Django 2.2.5 on 2019-11-18 19:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('webay', '0003_auto_20191118_1838'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='winner_notified',
            field=models.BooleanField(default=None),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('email_sent', models.BooleanField()),
                ('read_message', models.BooleanField()),
                ('recipient', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='message', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
