# Generated by Django 2.2.5 on 2019-11-18 20:50

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('webay', '0004_auto_20191118_1914'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Message',
            new_name='Notification',
        ),
    ]
