# Generated by Django 2.2.5 on 2019-11-22 10:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webay', '0005_auto_20191118_2050'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='winner_notified',
        ),
        migrations.AddField(
            model_name='notification',
            name='item',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='webay.Item'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='bid',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='notification',
            name='recipient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='notification', to=settings.AUTH_USER_MODEL),
        ),
    ]
